// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gasvlzvjwjwytyuwyzzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdhc3ZsenZqd2p3eXR5dXd5enpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjQ4OTEsImV4cCI6MjA2Mzg0MDg5MX0.fSIlTsoyID6-AVu8RMzjtC43jjz__7Lz2fbIZC1-sxI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);